// <auto-generated />
using System;
using ForgeTwin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForgeTwin.Migrations
{
    [DbContext(typeof(ForgeTwinDbContext))]
    [Migration("20260719112423_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForgeTwin.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int>("ReorderThreshold")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SKU");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Inventor__3214EC073CEFE6EE");

                    b.HasIndex(new[] { "SKU" }, "UQ__Inventor__CA1ECF0D8EEB032A")
                        .IsUnique();

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("ForgeTwin.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InstalledOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Machines__3214EC078F84F492");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("ForgeTwin.Models.MaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK__Maintena__3214EC07562E0EDA");

                    b.HasIndex("MachineId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("ForgeTwin.Models.ProductionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefectCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("UnitsProduced")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Producti__3214EC0700724099");

                    b.HasIndex("MachineId");

                    b.ToTable("ProductionLogs");
                });

            modelBuilder.Entity("ForgeTwin.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC079E4EAFD1");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4290B7D3C")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ForgeTwin.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK__WorkOrde__3214EC073F4D5B82");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("MachineId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("ForgeTwin.Models.WorkOrderInventoryItem", b =>
                {
                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("int");

                    b.HasKey("WorkOrderId", "InventoryItemId")
                        .HasName("PK__WorkOrde__BDCE7BDD582D1489");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("WorkOrderInventoryItems");
                });

            modelBuilder.Entity("ForgeTwin.Models.MaintenanceRecord", b =>
                {
                    b.HasOne("ForgeTwin.Models.Machine", "Machine")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_Machines");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("ForgeTwin.Models.ProductionLog", b =>
                {
                    b.HasOne("ForgeTwin.Models.Machine", "Machine")
                        .WithMany("ProductionLogs")
                        .HasForeignKey("MachineId")
                        .IsRequired()
                        .HasConstraintName("FK__Productio__Machi__4E88ABD4");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("ForgeTwin.Models.WorkOrder", b =>
                {
                    b.HasOne("ForgeTwin.Models.User", "AssignedToUser")
                        .WithMany("WorkOrders")
                        .HasForeignKey("AssignedToUserId")
                        .HasConstraintName("FK_WorkOrders_Users");

                    b.HasOne("ForgeTwin.Models.Machine", "Machine")
                        .WithMany("WorkOrders")
                        .HasForeignKey("MachineId")
                        .IsRequired()
                        .HasConstraintName("FK_WorkOrders_Machines");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("ForgeTwin.Models.WorkOrderInventoryItem", b =>
                {
                    b.HasOne("ForgeTwin.Models.InventoryItem", "InventoryItem")
                        .WithMany("WorkOrderInventoryItems")
                        .HasForeignKey("InventoryItemId")
                        .IsRequired()
                        .HasConstraintName("FK__WorkOrder__Inven__4AB81AF0");

                    b.HasOne("ForgeTwin.Models.WorkOrder", "WorkOrder")
                        .WithMany("WorkOrderInventoryItems")
                        .HasForeignKey("WorkOrderId")
                        .IsRequired()
                        .HasConstraintName("FK__WorkOrder__WorkO__49C3F6B7");

                    b.Navigation("InventoryItem");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("ForgeTwin.Models.InventoryItem", b =>
                {
                    b.Navigation("WorkOrderInventoryItems");
                });

            modelBuilder.Entity("ForgeTwin.Models.Machine", b =>
                {
                    b.Navigation("MaintenanceRecords");

                    b.Navigation("ProductionLogs");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("ForgeTwin.Models.User", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("ForgeTwin.Models.WorkOrder", b =>
                {
                    b.Navigation("WorkOrderInventoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
